// Auto-generado: listado de imágenes locales y pines.
// Fecha: 2025-11-14
// Nota: Metro requiere rutas estáticas en require(). No edites a mano, vuelve a ejecutar el generador si cambian los archivos.

// Módulos de imagen locales (require estático)
export const LocalImageModules: number[] = [
  require('../../assets/images/Amon_Investigator.jpeg'),
  require('../../assets/images/Amon_Strict.jpeg'),
  require('../../assets/images/Amon_vs_Kaneki.jpeg'),
  require('../../assets/images/Anteiku_Battle.jpeg'),
  require('../../assets/images/Aogiri_Attack.jpeg'),
  require('../../assets/images/Aogiri_Headquarters.jpeg'),
  require('../../assets/images/Arima_Pack.jpeg'),
  require('../../assets/images/Arima_vs_Kaneki.jpeg'),
  require('../../assets/images/Arima_VS.jpeg'),
  require('../../assets/images/Arima_WhiteReaper.jpeg'),
  require('../../assets/images/BloodMoon_Tokyo.jpeg'),
  require('../../assets/images/BrokenChains_Kaneki.jpeg'),
  require('../../assets/images/BrokenMask.jpeg'),
  require('../../assets/images/CCG_Operation.jpeg'),
  require('../../assets/images/CCG_Strike.jpeg'),
  require('../../assets/images/CCG_vs_Ghouls.jpeg'),
  require('../../assets/images/Clown_Chaos.jpeg'),
  require('../../assets/images/Cochlea_PrisonBreak.jpeg'),
  require('../../assets/images/DarkAesthetic_Wall.jpeg'),
  require('../../assets/images/DarkAnime_Pack.jpeg'),
  require('../../assets/images/DarkTokyo_Street.jpeg'),
  require('../../assets/images/Dragon_Kaneki.jpeg'),
  require('../../assets/images/Eto_GhoulForm.jpeg'),
  require('../../assets/images/Eto_OneEyedOwl.jpeg'),
  require('../../assets/images/Eto_Pack.jpeg'),
  require('../../assets/images/Eyes_Transformation.jpeg'),
  require('../../assets/images/Ghoul_Aura.jpeg'),
  require('../../assets/images/Ghoul_Collection01.jpg'),
  require('../../assets/images/Ghoul_Collection02.jpg'),
  require('../../assets/images/Ghoul_Collection03.jpeg'),
  require('../../assets/images/Ghoul_EyeGlow.jpeg'),
  require('../../assets/images/Ghoul_Mask_Collection.jpeg'),
  require('../../assets/images/Ghoul_ShadowsFolder.jpeg'),
  require('../../assets/images/Ghoul_Universe.jpeg'),
  require('../../assets/images/Ghoul_War.jpeg'),
  require('../../assets/images/Gourmet_vs_Kaneki.jpeg'),
  require('../../assets/images/Haise_vs_TorMent.jpeg'),
  require('../../assets/images/Hide_Mystery.jpeg'),
  require('../../assets/images/Hide_Smile.jpeg'),
  require('../../assets/images/Hide_YellowFriend.jpeg'),
  require('../../assets/images/Hinami_Child.jpeg'),
  require('../../assets/images/Hinami_Ghoul.jpeg'),
  require('../../assets/images/Hinami_Rescue.jpeg'),
  require('../../assets/images/Jason_Torture.jpeg'),
  require('../../assets/images/Juuzo_Battle.jpeg'),
  require('../../assets/images/Juuzo_Pack.jpeg'),
  require('../../assets/images/Juuzo_Smile.jpeg'),
  require('../../assets/images/Juuzo_Suzuya.jpeg'),
  require('../../assets/images/Kagune_Flames.jpeg'),
  require('../../assets/images/Kaneki_Antiguo.jpeg'),
  require('../../assets/images/Kaneki_ArtRed.jpeg'),
  require('../../assets/images/Kaneki_ArtworkStyle.jpeg'),
  require('../../assets/images/Kaneki_BlackReaper.jpeg'),
  require('../../assets/images/Kaneki_BloodyWalk.jpeg'),
  require('../../assets/images/Kaneki_Centipede.jpeg'),
  require('../../assets/images/Kaneki_CityLights.jpeg'),
  require('../../assets/images/Kaneki_DarkVibes.jpeg'),
  require('../../assets/images/Kaneki_DragonForm.jpeg'),
  require('../../assets/images/Kaneki_Emotional.jpeg'),
  require('../../assets/images/Kaneki_Flames.jpeg'),
  require('../../assets/images/Kaneki_HaiseMode.jpeg'),
  require('../../assets/images/Kaneki_HalfGhoul.jpeg'),
  require('../../assets/images/Kaneki_JasonChair.jpeg'),
  require('../../assets/images/Kaneki_MaskOn.jpeg'),
  require('../../assets/images/Kaneki_MentalBreak.jpeg'),
  require('../../assets/images/Kaneki_Mirror.jpeg'),
  require('../../assets/images/Kaneki_OneEyedGhoul.jpeg'),
  require('../../assets/images/Kaneki_Pack.jpeg'),
  require('../../assets/images/Kaneki_Rebirth.jpeg'),
  require('../../assets/images/Kaneki_SnowFight.jpeg'),
  require('../../assets/images/Kaneki_vs_Amon.jpeg'),
  require('../../assets/images/Kaneki_vs_Jason.jpeg'),
  require('../../assets/images/LastFinalBattle.jpeg'),
  require('../../assets/images/Mask_CloseUp.jpeg'),
  require('../../assets/images/Masked_Archive.jpeg'),
  require('../../assets/images/MaskedShadow.jpeg'),
  require('../../assets/images/Owl_Shadow.jpeg'),
  require('../../assets/images/Owl_vs_Arima.jpeg'),
  require('../../assets/images/Purple_Rize_Aura.jpeg'),
  require('../../assets/images/Quinx_TeamBattle.jpeg'),
  require('../../assets/images/Raid_on_CCG.jpeg'),
  require('../../assets/images/RedAndBlack_Set.jpeg'),
  require('../../assets/images/RedBlack_Theme.jpeg'),
  require('../../assets/images/Rize_AccidentScene.jpeg'),
  require('../../assets/images/Rize_DemonLook.jpeg'),
  require('../../assets/images/Rize_GhoulForm.jpeg'),
  require('../../assets/images/Rize_Hunter.jpeg'),
  require('../../assets/images/Rize_Pack.jpeg'),
  require('../../assets/images/Rize_PurpleHair.jpeg'),
  require('../../assets/images/Rose_Gourmet.jpeg'),
  require('../../assets/images/Rue_Island.jpeg'),
  require('../../assets/images/TG_ArtworkFolder.jpeg'),
  require('../../assets/images/TG_BattleScenes.jpeg'),
  require('../../assets/images/TG_BestMoments.jpeg'),
  require('../../assets/images/TG_Characters_Set.jpeg'),
  require('../../assets/images/TG_DarkEdition.jpeg'),
  require('../../assets/images/TG_EmotionalScenes.jpeg'),
  require('../../assets/images/TG_EpicSet.jpeg'),
  require('../../assets/images/TG_IconicShots.jpeg'),
  require('../../assets/images/TG_LegendaryMoments.jpeg'),
  require('../../assets/images/TG_Re_Collection.jpeg'),
  require('../../assets/images/TG_SpecialEdition.jpeg'),
  require('../../assets/images/TG_UltraPack.jpeg'),
  require('../../assets/images/TG_Wallpapers_HD.jpeg'),
  require('../../assets/images/Tokyo_RedCity.jpeg'),
  require('../../assets/images/TokyoGhoul_AestheticRed.jpeg'),
  require('../../assets/images/TokyoGhoul_Gallery.png'),
  require('../../assets/images/Touka_BattleMode.jpeg'),
  require('../../assets/images/Touka_BunnyMask.jpeg'),
  require('../../assets/images/Touka_DigitalArt.jpeg'),
  require('../../assets/images/Touka_NightSky.jpeg'),
  require('../../assets/images/Touka_Pack.jpeg'),
  require('../../assets/images/Touka_RainyNight.jpeg'),
  require('../../assets/images/Touka_Re.jpeg'),
  require('../../assets/images/Touka_Smile.jpeg'),
  require('../../assets/images/Touka_vs_Ayato.jpeg'),
  require('../../assets/images/Touka_Waitress.jpeg'),
  require('../../assets/images/Tsukiyama_Crazy.jpeg'),
  require('../../assets/images/WhatsApp_2025_11_14_104306_1.jpeg'),
  require('../../assets/images/WhatsApp_2025_11_14_104306_2.jpeg'),
  require('../../assets/images/WhatsApp_2025_11_14_104306_3.jpeg'),
  require('../../assets/images/WhiteHair_Awakening.jpeg'),
  require('../../assets/images/WhiteHair_Smoke.jpeg'),
];

// Construir los pines locales a partir de los módulos con IDs únicos
export const LocalPins = LocalImageModules.map((img, idx) => ({
  id: `local_${idx}`, // ID único basado solo en el índice
  imageUri: img,
  title: `Imagen local ${idx + 1}`,
  description: 'Imagen agregada por el usuario',
  author: 'Usuario',
  likes: 0,
  isLiked: false,
  isSaved: false,
}));

// Real Tokyo Ghoul inspired images from high-quality sources
export const TokyoGhoulImages = {
  kaneki1: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&h=600&fit=crop&crop=center',
  kaneki2: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop&crop=center',
  kaneki3: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=600&fit=crop&crop=center',
  touka: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop&crop=center',
  tokyoGhoul: 'https://images.unsplash.com/photo-1626354227941-7d2b9b0e3b23?w=800&h=600&fit=crop&crop=center',
};

// Sample pins data with real Tokyo Ghoul images
export const SamplePins = [
  {
    id: '1',
    imageUri: TokyoGhoulImages.kaneki1,
    title: 'Kaneki Ken - Ghoul Form',
    description: 'Kaneki en su forma de ghoul con ojos rojos intensos y máscara característica',
    author: 'TokyoGhoulFan',
    likes: 342,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '2',
    imageUri: TokyoGhoulImages.kaneki2,
    title: 'Tokyo Ghoul Artwork',
    description: 'Arte oficial de Tokyo Ghoul con Kaneki mostrando su transformación',
    author: 'AnimeArtist',
    likes: 528,
    isLiked: true,
    isSaved: true,
  },
  {
    id: '3',
    imageUri: TokyoGhoulImages.kaneki3,
    title: 'Kaneki Transformation',
    description: 'La transformación épica de Kaneki con su kagune desplegado',
    author: 'MangaReader',
    likes: 289,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '4',
    imageUri: TokyoGhoulImages.touka,
    title: 'Touka Kirishima',
    description: 'Touka en acción mostrando sus habilidades de combate',
    author: 'CosplayMaster',
    likes: 167,
    isLiked: true,
    isSaved: false,
  },
  {
    id: '5',
    imageUri: TokyoGhoulImages.tokyoGhoul,
    title: 'Tokyo Ghoul Wallpaper',
    description: 'Wallpaper HD de Tokyo Ghoul con atmósfera oscura y misteriosa',
    author: 'WallpaperCreator',
    likes: 456,
    isLiked: false,
    isSaved: true,
  },
];

// Additional Tokyo Ghoul themed images for variety
export const ExtraTokyoGhoulImages = [
  {
    id: '6',
    imageUri: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=600&fit=crop&crop=center',
    title: 'Cafe Anteiku',
    description: 'El icónico café donde trabajan los ghouls',
    author: 'AnteikuFan',
    likes: 234,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '7',
    imageUri: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=600&fit=crop&crop=center',
    title: 'Ghoul Mask Collection',
    description: 'Colección de las máscaras más icónicas de Tokyo Ghoul',
    author: 'MaskMaker',
    likes: 198,
    isLiked: true,
    isSaved: true,
  },
  {
    id: '8',
    imageUri: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&h=600&fit=crop&crop=center',
    title: 'CCG Investigators',
    description: 'Los investigadores de la Comisión de Contramedidas contra Ghouls',
    author: 'CCGOfficial',
    likes: 156,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '9',
    imageUri: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&crop=center',
    title: 'Kagune Powers',
    description: 'Diferentes tipos de kagune y sus habilidades únicas',
    author: 'GhoulBiology',
    likes: 312,
    isLiked: true,
    isSaved: false,
  },
  {
    id: '10',
    imageUri: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&h=600&fit=crop&crop=center',
    title: 'Tokyo Ghoul Scenes',
    description: 'Escenas memorables de la serie Tokyo Ghoul',
    author: 'SceneCollector',
    likes: 445,
    isLiked: false,
    isSaved: true,
  },
];