// Imágenes locales agregadas por el usuario
// Usar una función getter para evitar que require() se ejecute durante la inicialización
export const LocalImages = {
  get img1() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.40 PM (1).jpeg'); },
  get img2() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.40 PM.jpeg'); },
  get img3() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.41 PM (1).jpeg'); },
  get img4() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.41 PM (2).jpeg'); },
  get img5() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.41 PM (3).jpeg'); },
  get img6() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.41 PM (4).jpeg'); },
  get img7() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.41 PM (5).jpeg'); },
  get img8() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.41 PM (6).jpeg'); },
  get img9() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.41 PM.jpeg'); },
  get img10() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.42 PM (1).jpeg'); },
  get img11() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.42 PM (2).jpeg'); },
  get img12() { return require('../../assets/images/WhatsApp Image 2025-09-28 at 4.11.42 PM.jpeg'); },
};

// Pins con imágenes locales
export const LocalPins = [
  {
    id: 'l1',
    imageUri: LocalImages.img1,
    title: 'Imagen local 1',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l2',
    imageUri: LocalImages.img2,
    title: 'Imagen local 2',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l3',
    imageUri: LocalImages.img3,
    title: 'Imagen local 3',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l4',
    imageUri: LocalImages.img4,
    title: 'Imagen local 4',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l5',
    imageUri: LocalImages.img5,
    title: 'Imagen local 5',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l6',
    imageUri: LocalImages.img6,
    title: 'Imagen local 6',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l7',
    imageUri: LocalImages.img7,
    title: 'Imagen local 7',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l8',
    imageUri: LocalImages.img8,
    title: 'Imagen local 8',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l9',
    imageUri: LocalImages.img9,
    title: 'Imagen local 9',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l10',
    imageUri: LocalImages.img10,
    title: 'Imagen local 10',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l11',
    imageUri: LocalImages.img11,
    title: 'Imagen local 11',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
  {
    id: 'l12',
    imageUri: LocalImages.img12,
    title: 'Imagen local 12',
    description: 'Imagen agregada por el usuario',
    author: 'Usuario',
    likes: 0,
    isLiked: false,
    isSaved: false,
  },
];
// Real Tokyo Ghoul inspired images from high-quality sources
export const TokyoGhoulImages = {
  kaneki1: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&h=600&fit=crop&crop=center',
  kaneki2: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800&h=600&fit=crop&crop=center',
  kaneki3: 'https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=600&fit=crop&crop=center',
  touka: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop&crop=center',
  tokyoGhoul: 'https://images.unsplash.com/photo-1626354227941-7d2b9b0e3b23?w=800&h=600&fit=crop&crop=center',
};

// Sample pins data with real Tokyo Ghoul images
export const SamplePins = [
  {
    id: '1',
    imageUri: TokyoGhoulImages.kaneki1,
    title: 'Kaneki Ken - Ghoul Form',
    description: 'Kaneki en su forma de ghoul con ojos rojos intensos y máscara característica',
    author: 'TokyoGhoulFan',
    likes: 342,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '2',
    imageUri: TokyoGhoulImages.kaneki2,
    title: 'Tokyo Ghoul Artwork',
    description: 'Arte oficial de Tokyo Ghoul con Kaneki mostrando su transformación',
    author: 'AnimeArtist',
    likes: 528,
    isLiked: true,
    isSaved: true,
  },
  {
    id: '3',
    imageUri: TokyoGhoulImages.kaneki3,
    title: 'Kaneki Transformation',
    description: 'La transformación épica de Kaneki con su kagune desplegado',
    author: 'MangaReader',
    likes: 289,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '4',
    imageUri: TokyoGhoulImages.touka,
    title: 'Touka Kirishima',
    description: 'Touka en acción mostrando sus habilidades de combate',
    author: 'CosplayMaster',
    likes: 167,
    isLiked: true,
    isSaved: false,
  },
  {
    id: '5',
    imageUri: TokyoGhoulImages.tokyoGhoul,
    title: 'Tokyo Ghoul Wallpaper',
    description: 'Wallpaper HD de Tokyo Ghoul con atmósfera oscura y misteriosa',
    author: 'WallpaperCreator',
    likes: 456,
    isLiked: false,
    isSaved: true,
  },
];

// Additional Tokyo Ghoul themed images for variety
export const ExtraTokyoGhoulImages = [
  {
    id: '6',
    imageUri: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&h=600&fit=crop&crop=center',
    title: 'Cafe Anteiku',
    description: 'El icónico café donde trabajan los ghouls',
    author: 'AnteikuFan',
    likes: 234,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '7',
    imageUri: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&h=600&fit=crop&crop=center',
    title: 'Ghoul Mask Collection',
    description: 'Colección de las máscaras más icónicas de Tokyo Ghoul',
    author: 'MaskMaker',
    likes: 198,
    isLiked: true,
    isSaved: true,
  },
  {
    id: '8',
    imageUri: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&h=600&fit=crop&crop=center',
    title: 'CCG Investigators',
    description: 'Los investigadores de la Comisión de Contramedidas contra Ghouls',
    author: 'CCGOfficial',
    likes: 156,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '9',
    imageUri: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800&h=600&fit=crop&crop=center',
    title: 'Kagune Powers',
    description: 'Diferentes tipos de kagune y sus habilidades únicas',
    author: 'GhoulBiology',
    likes: 312,
    isLiked: true,
    isSaved: false,
  },
  {
    id: '10',
    imageUri: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?w=800&h=600&fit=crop&crop=center',
    title: 'Tokyo Ghoul Scenes',
    description: 'Escenas memorables de la serie Tokyo Ghoul',
    author: 'SceneCollector',
    likes: 445,
    isLiked: false,
    isSaved: true,
  },
];